version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "nghiatran123/netflix-backend"
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "nghiatran123/netflix-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"